# Generated by Django 4.1.5 on 2023-01-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_event_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
