# Generated by Django 4.1.5 on 2023-02-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_event_user_id_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='beamer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='chairs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='ethernet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='room',
            name='tables',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='wlan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
