# Generated by Django 4.1.5 on 2023-02-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_room_beamer_room_chairs_room_ethernet_room_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
